# DO NOT TOUCH THIS FILE
# Please speak to SudoVanilla (Korbs) if you have any issues.

name: Deploy Docs

on:
  push:
    branches: [ "starlight" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      # Install Dependenices
      - run: bun install
      # Build Docs
      - run: cd ../../
      - run: npm install sharp.
      - run: rm package-lock.json
      - run: bun run build
      # Add to NGINX
      - run: mv dist/ docs/
      - run: cp -R docs/ /home/tea/sites/
